# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('due', models.IntegerField()),
                ('reported', models.IntegerField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='frontend.Sponsor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set([('sponsor', 'date')]),
        ),
    ]
