# Generated by Django 2.0 on 2017-12-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20171228_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
