# Generated by Django 2.0 on 2017-12-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_ranking_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
