# Generated by Django 2.0 on 2017-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_ranking_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
