# Generated by Django 2.0 on 2017-12-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20171228_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ('rank', 'sponsor__name')},
        ),
        migrations.AlterField(
            model_name='trial',
            name='registry_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
