# Generated by Django 2.0 on 2017-12-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20171228_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
