# Generated by Django 2.0 on 2018-01-03 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20171228_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='is_current',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='updated_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
