# Generated by Django 2.0 on 2018-01-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20180103_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
