# Generated by Django 2.0 on 2018-01-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20180103_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='id',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='major',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trial',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Sponsor'),
        ),
    ]
