# Generated by Django 2.0 on 2018-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20180104_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ('date', 'rank', 'sponsor__name')},
        ),
        migrations.AddField(
            model_name='ranking',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
