# Generated by Django 2.0 on 2018-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20180111_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='is_industry_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
