# Generated by Django 2.0 on 2018-01-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_trial_is_industry_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='is_industry_sponsor',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_industry_sponsor',
            field=models.NullBooleanField(default=None),
        ),
    ]
