# Generated by Django 2.0 on 2018-01-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20180115_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='due_date',
        ),
        migrations.AddField(
            model_name='trial',
            name='has_results',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='trial',
            name='results_due',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
