# Generated by Django 2.0 on 2018-01-17 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20180116_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='first_seen_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trial',
            name='reported_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('completed-late', 'Completed (late)'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='trial',
            name='updated_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trial',
            name='registry_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
