# Generated by Django 2.0 on 2018-01-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20180118_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ('completion_date',)},
        ),
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('ongoing', 'Ongoing'), ('reported', 'Reported'), ('reported-late', 'Reported (late)')], default='ongoing', max_length=20),
        ),
    ]
