# Generated by Django 2.0 on 2018-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20180122_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='days_late',
            field=models.IntegerField(default=0),
        ),
    ]
