# Generated by Django 2.0 on 2018-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20180122_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('ongoing', 'Ongoing'), ('reported', 'Reported'), ('qa', 'Under QA'), ('reported-late', 'Reported (late)')], default='ongoing', max_length=20),
        ),
    ]
