# Generated by Django 2.0 on 2018-02-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_auto_20180207_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_to_regulator', models.DateField()),
                ('returned_to_sponsor', models.DateField(blank=True, null=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Trial')),
            ],
        ),
    ]
