# Generated by Django 2.0 on 2018-02-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_trialqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='no_longer_on_website',
            field=models.BooleanField(default=False),
        ),
    ]
