# Generated by Django 2.0 on 2018-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_auto_20180214_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='days_late',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ranking',
            name='finable_days_late',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
