# Generated by Django 2.0.3 on 2018-03-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_auto_20180226_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ('completion_date', 'start_date', 'id')},
        ),
    ]
