# Generated by Django 2.0.3 on 2018-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_auto_20180308_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='reported_late',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='reported_on_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
