# Generated by Django 2.0.3 on 2018-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_auto_20180312_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='overdue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
