# Generated by Django 2.0.3 on 2018-03-19 15:17

from django.db import migrations, models


def set_previous_status(apps, schema_editor):
    Trial = apps.get_model("frontend", "Trial")
    Trial.objects.all().update(previous_status=models.F('status'))

def noop(*args):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_ranking_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('overdue', 'Overdue'), ('ongoing', 'Ongoing'), ('reported', 'Reported'), ('reported-late', 'Reported (late)')], default='ongoing', max_length=20, null=True),
        ),
        migrations.RunPython(set_previous_status, noop)
    ]
