# Generated by Django 2.0.3 on 2018-03-20 13:07

from django.db import migrations
from frontend.models import Trial


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_trial_previous_status'),
    ]

    operations = [
        migrations.RunSQL(
            [
                ("UPDATE frontend_trial SET status = %s WHERE no_longer_on_website is true",
                 [Trial.STATUS_NO_LONGER_ACT])],
            [
                ("UPDATE frontend_trial SET no_longer_on_website = true WHERE status = %s",
                 [Trial.STATUS_NO_LONGER_ACT])],
        )
    ]
