# Generated by Django 2.0.3 on 2018-03-20 13:07

from django.db import migrations
from frontend.models import Trial


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_update_status_from_no_longer_on_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='no_longer_on_website',
        ),
    ]
