# Generated by Django 2.0.3 on 2018-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_remove_trial_no_longer_on_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialqa',
            name='cancellation_date_assumed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='trialqa',
            name='cancelled_by_sponsor',
            field=models.DateField(blank=True, null=True),
        ),
    ]
