# Generated by Django 2.0.3 on 2018-05-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_auto_20180521_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialqa',
            old_name='cancellation_date_assumed',
            new_name='cancellation_date_inferred',
        ),
    ]
