# Generated by Django 2.1.4 on 2018-12-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0035_manual_pk_fix'),
        ('frontend', '0034_auto_20181210_1321'),
    ]

    operations = [
    ]
