"""
Django settings for clinicaltrials project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
from frontend.settings import *

LOGGING["handlers"]["applogfile"]["filename"] = os.path.join(
    PROJECT_ROOT, "clinicaltrials.log"
)
