service: default
runtime: python37

handlers:
- url: /static
  static_dir: static/
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  CLINICALTRIALS_SECRET_KEY: 'asd' # random longish string for sessions
  CLINICALTRIALS_HTTP_MANAGEMENT_SECRET: 'asd' # random longish string for securing REST endpoints
  CLINICALTRIALS_DEBUG: 'yes' # yes or no
  CLINICALTRIALS_GOOGLE_TRACKING_ID: '' # optional Analytics id, e.g. UA-nnnnnnnn-n
  CLINICALTRIALS_DB: 'clinicaltrials'
  CLINICALTRIALS_DB_NAME: 'fdaaa'
  CLINICALTRIALS_DB_PASS: 'fdaaa'
  #GOOGLE_APPLICATION_CREDENTIALS: ''
  SLACK_GENERAL_POST_KEY: 'https://hooks.slack.com/services/T1234'
  TWITTER_CONSUMER_SECRET: ''
  TWITTER_ACCESS_TOKEN_SECRET: ''
  GOOGLE_SERVICE_ACCOUNT_FILE_FDAAA: '/srv/clinicaltrials-credentials.json'  # XXX don't like hard-coding the path; can probably rely on service account?  (This is used by the vendored app)
